export const defaultReferenceSeeds = {
  colors: [
    { name: 'Bianco', hexCode: '#FFFFFF', sortOrder: 1 },
    { name: 'Panna', hexCode: '#FFFDD0', sortOrder: 2 },
    { name: 'Beige', hexCode: '#F5F5DC', sortOrder: 3 },
    { name: 'Cammello', hexCode: '#C19A6B', sortOrder: 4 },
    { name: 'Cuoio', hexCode: '#D2B48C', sortOrder: 5 },
    { name: 'Marrone', hexCode: '#A52A2A', sortOrder: 6 },
    { name: 'Nero', hexCode: '#000000', sortOrder: 7 },
    { name: 'Antracite', hexCode: '#36454F', sortOrder: 8 },
    { name: 'Grigio', hexCode: '#808080', sortOrder: 9 },
    { name: 'Grigio chiaro', hexCode: '#D3D3D3', sortOrder: 10 },
    { name: 'Argento', hexCode: '#C0C0C0', sortOrder: 11 },
    { name: 'Oro', hexCode: '#FFD700', sortOrder: 12 },
    { name: 'Blu navy', hexCode: '#000080', sortOrder: 13 },
    { name: 'Blu', hexCode: '#0000FF', sortOrder: 14 },
    { name: 'Blu reale', hexCode: '#4169E1', sortOrder: 15 },
    { name: 'Celeste', hexCode: '#87CEEB', sortOrder: 16 },
    { name: 'Azzurro chiaro', hexCode: '#ADD8E6', sortOrder: 17 },
    { name: 'Verde scuro', hexCode: '#006400', sortOrder: 18 },
    { name: 'Verde', hexCode: '#008000', sortOrder: 19 },
    { name: 'Verde oliva', hexCode: '#808000', sortOrder: 20 },
    { name: 'Verde petrolio', hexCode: '#008080', sortOrder: 21 },
    { name: 'Verde menta', hexCode: '#98FF98', sortOrder: 22 },
    { name: 'Giallo', hexCode: '#FFFF00', sortOrder: 23 },
    { name: 'Senape', hexCode: '#FFDB58', sortOrder: 24 },
    { name: 'Arancione', hexCode: '#FFA500', sortOrder: 25 },
    { name: 'Corallo', hexCode: '#FF7F50', sortOrder: 26 },
    { name: 'Rosso', hexCode: '#FF0000', sortOrder: 27 },
    { name: 'Rosso scuro', hexCode: '#8B0000', sortOrder: 28 },
    { name: 'Bordeaux', hexCode: '#800020', sortOrder: 29 },
    { name: 'Rosa', hexCode: '#FFC0CB', sortOrder: 30 },
    { name: 'Fucsia', hexCode: '#FF69B4', sortOrder: 31 },
    { name: 'Viola', hexCode: '#800080', sortOrder: 32 },
    { name: 'Violetto', hexCode: '#EE82EE', sortOrder: 33 },
    { name: 'Lavanda', hexCode: '#E6E6FA', sortOrder: 34 },
    { name: 'Multicolore', hexCode: null, sortOrder: 35 },
  ],
  brands: [
    'Zara','H&M','Uniqlo','Gap','Levi\'s','Nike','Adidas','Puma','Ralph Lauren','Tommy Hilfiger','Calvin Klein','Hugo Boss','Armani','Gucci','Prada','Louis Vuitton','Burberry','Versace','Mango','Pull&Bear','Bershka','Stradivarius','Massimo Dutti','Reserved','C&A','Primark','Marks & Spencer','Next','Lacoste','Fred Perry','Stone Island','North Face','Patagonia','Columbia','Timberland','Dr. Martens','Converse','Vans','New Balance','Reebok','Under Armour','Lululemon','Gymshark','ASOS','Cos','Arket','Altro / Sconosciuto',
  ].map((name) => ({ name })),
  seasons: [
    { name: 'Autunno', icon: '🍂', sortOrder: 1 },
    { name: 'Inverno', icon: '❄️', sortOrder: 2 },
    { name: 'Primavera', icon: '🌸', sortOrder: 3 },
    { name: 'Estate', icon: '☀️', sortOrder: 4 },
    { name: 'Tutte le stagioni', icon: '🌍', sortOrder: 5 },
  ],
  temperatures: [
    { name: 'Molto freddo', icon: '🥶', sortOrder: 1 },
    { name: 'Freddo', icon: '🧊', sortOrder: 2 },
    { name: 'Fresco', icon: '🌬️', sortOrder: 3 },
    { name: 'Temperato', icon: '😐', sortOrder: 4 },
    { name: 'Mite', icon: '🌤️', sortOrder: 5 },
    { name: 'Caldo', icon: '☀️', sortOrder: 6 },
    { name: 'Molto caldo', icon: '🔥', sortOrder: 7 },
  ],
  useCases: [
    { name: 'Casa', icon: '🏠', sortOrder: 1 },
    { name: 'Relax', icon: '🛋️', sortOrder: 2 },
    { name: 'Notte', icon: '😴', sortOrder: 3 },
    { name: 'Casual', icon: '👕', sortOrder: 4 },
    { name: 'Viaggio', icon: '✈️', sortOrder: 5 },
    { name: 'Lavoro', icon: '💼', sortOrder: 6 },
    { name: 'Formale', icon: '👔', sortOrder: 7 },
    { name: 'Matrimonio', icon: '💒', sortOrder: 8 },
    { name: 'Festa', icon: '🎉', sortOrder: 9 },
    { name: 'Sport', icon: '🏃', sortOrder: 10 },
    { name: 'Palestra', icon: '💪', sortOrder: 11 },
    { name: 'Outdoor', icon: '🏕️', sortOrder: 12 },
    { name: 'Spiaggia', icon: '🏖️', sortOrder: 13 },
  ],
  fits: [
    { name: 'Aderente', sortOrder: 1 },
    { name: 'Skinny', sortOrder: 2 },
    { name: 'Affusolato', sortOrder: 3 },
    { name: 'Regolare', sortOrder: 4 },
    { name: 'Dritto', sortOrder: 5 },
    { name: 'Comodo', sortOrder: 6 },
    { name: 'Ampio', sortOrder: 7 },
    { name: 'Oversize', sortOrder: 8 },
    { name: 'Svasato', sortOrder: 9 },
    { name: 'Bootcut', sortOrder: 10 },
    { name: 'Sportivo', sortOrder: 11 },
    { name: 'Squadrato', sortOrder: 12 },
    { name: 'Corto', sortOrder: 13 },
  ],
  materials: [
    { name: 'Cotone', sortOrder: 1 },
    { name: 'Lino', sortOrder: 2 },
    { name: 'Canapa', sortOrder: 3 },
    { name: 'Bambu', sortOrder: 4 },
    { name: 'Lana', sortOrder: 5 },
    { name: 'Lana merino', sortOrder: 6 },
    { name: 'Cachemire', sortOrder: 7 },
    { name: 'Seta', sortOrder: 8 },
    { name: 'Modal', sortOrder: 9 },
    { name: 'Viscosa', sortOrder: 10 },
    { name: 'Rayon', sortOrder: 11 },
    { name: 'Tencel', sortOrder: 12 },
    { name: 'Poliestere', sortOrder: 13 },
    { name: 'Poliestere riciclato', sortOrder: 14 },
    { name: 'Nylon', sortOrder: 15 },
    { name: 'Acrilico', sortOrder: 16 },
    { name: 'Lycra', sortOrder: 17 },
    { name: 'Spandex', sortOrder: 18 },
    { name: 'Denim', sortOrder: 19 },
    { name: 'Tela', sortOrder: 20 },
    { name: 'Jersey', sortOrder: 21 },
    { name: 'Tweed', sortOrder: 22 },
    { name: 'Velluto', sortOrder: 23 },
    { name: 'Velluto a coste', sortOrder: 24 },
    { name: 'Pile', sortOrder: 25 },
    { name: 'Pelle', sortOrder: 26 },
    { name: 'Camoscio', sortOrder: 27 },
    { name: 'Pizzo', sortOrder: 28 },
    { name: 'Chiffon', sortOrder: 29 },
    { name: 'Raso', sortOrder: 30 },
  ],
  types: [
    'T-shirt',
    'Polo',
    'Camicia',
    'Camicia maniche lunghe',
    'Camicia maniche corte',
    'Blusa',
    'Top',
    'Canotta',
    'Maglione',
    'Cardigan',
    'Felpa',
    'Hoodie',
    'Giacca',
    'Blazer',
    'Cappotto',
    'Piumino',
    'Trench',
    'Gilet',
    'Jeans',
    'Pantaloni',
    'Chino',
    'Shorts',
    'Joggers',
    'Leggings',
    'Gonna',
    'Vestito',
    'Tuta',
    'Completo',
    'Intimo',
    'Pigiama',
    'Costume',
    'Scarpe da ginnastica',
    'Sneakers',
    'Mocassini',
    'Derby',
    'Scarpe eleganti',
    'Stivali',
    'Stivaletti',
    'Sandali',
    'Ciabatte',
    'Infradito',
  ].map((name) => ({ name })),
} as const;